lymphoids <- c("CD4+ memory T-cells",
               "CD4+ naive T-cells",
               "CD4+ T-cells",
               "CD4+ Tcm",
               "CD4+ Tem",
               "CD8+ naive T-cells",
               "CD8+ T-cells",
               "CD8+ Tcm",
               "CD8+ Tem",
               "Tregs",
               "Th1 cells",
               "Th2 cells",
               "Tgd cells",
               "NK cells",
               "NKT",
               "B-cells",
               "naive B-cells",
               "Memory B-cells",
               "Class-switched memory B-cells",
               "pro B-cells",
               "Plasma cells")

lymphoids.reduced <- c(#"CD4+ memory T-cells",
               #"CD4+ naive T-cells",
               "CD4+ Tcm",
               "CD4+ Tem",
               #"CD8+ naive T-cells",
               "CD8+ Tcm",
               "CD8+ Tem",
               "Tregs",
               #"Th1 cells",
               #"Th2 cells",
               "Tgd cells",
               "NK cells",
               #"NKT",
               "naive B-cells",
               "Memory B-cells",
               "Class-switched memory B-cells",
               "Plasma cells")

stem <- c("aDC",
          "HSC",
          "CLP",
          "CMP",
          "GMP",
          "MEP",
          "MPP",
          "Megakaryocytes",
          "Erythrocytes",
          "Platelets")

stromal <- c("MSC",
             "Adipocytes",
             "Preadipocytes",
             "Fibroblasts",
             "Pericytes",
             "Endothelial cells",
             "mv Endothelial cells",
             "ly Endothelial cells",
             "Smooth muscle",
             "Chondrocytes",
             "Osteoblast",
             "Skeletal muscle",
             "Myocytes")

myeloids <- c("Monocytes",
              "Macrophages",
              "Macrophages M1",
              "Macrophages M2",
              "DC" ,
              "cDC",
              "pDC",
              "iDC",
              "Neutrophils",
              "Eosinophils",
              "Mast cells",
              "Basophils")

scores <- c("ImmuneScore",
            "StromaScore",
            "MicroenvironmentScore")

others <- c("Epithelial cells",
            "Sebocytes",
            "Keratinocytes",
            "Mesangial cells",
            "Hepatocytes",
            "Melanocytes",
            "Astrocytes",
            "Neurons")

prognostic <- c("Th1 cells",
                 "CD8+ Tcm",
                 "CD8+ Tem",
                 "NK cells",
                 "Macrophages M1",
                 "Tregs",
                 "Th2 cells",
                 "Macrophages M2")
